name: Mod publication

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
